-- Create a High Noon Showdown tournament for tomorrow at 12 PM
INSERT INTO tournaments (
  id,
  title,
  description,
  game_id,
  platform,
  tournament_type,
  max_participants,
  entry_fee,
  prize_pool,
  registration_opens_at,
  registration_closes_at,
  start_time,
  tournament_status,
  status,
  creator_id,
  poster_title,
  collectible_series,
  season_number,
  episode_number,
  cover_art_url,
  proof_required,
  auto_verification,
  verification_threshold
) VALUES (
  gen_random_uuid(),
  'High Noon Showdown - COD Western Challenge',
  'When the clock strikes noon, only the fastest guns survive. COD meets the Wild West in this ultimate cowboy showdown.',
  '2b277553-0c32-4e8e-8bbf-718e98afeb5b',
  'Xbox',
  'single_elimination',
  32,
  50.00,
  1600.00,
  NOW(),
  (CURRENT_DATE + INTERVAL '1 day' + TIME '11:45:00'),
  (CURRENT_DATE + INTERVAL '1 day' + TIME '12:00:00'),
  'registration_open',
  'in_progress',
  (SELECT user_id FROM profiles WHERE is_admin = true LIMIT 1),
  'High Noon Showdown: COD Western Challenge',
  'Wild West Gaming Series',
  1,
  1,
  '/assets/sunday-showdown-12noon.jpg',
  true,
  true,
  0.85
);